---
  
# Ckeck packages
- setup:
    filter: ansible*

- name: Ensure all packages have been installed
  package:
    state: present 
    name: "{{ item }}"
  with_items:
        - git
        - tar
       
