---
   
- file: 
     path: /tmp/check.tmp
     state: absent
  run_once: true
  delegate_to: 127.0.0.1
  ignore_errors: true
   
- file: 
     path: /tmp/check.tmp
     state: touch
  run_once: true
  delegate_to: 127.0.0.1
     
- name: Pinging ssh protocol
  shell: "nmap -p 22 {{inventory_hostname}} 2>/dev/null | grep -q open && exit 0 ||
         nmap -p 22  {{hostvars[inventory_hostname].ansible_ssh_host | default('')}} 2>/dev/null 
                           | grep -q open && exit 0 ||
         nmap -p {{hostvars[inventory_hostname].ansible_ssh_port | default('')}} 
                 {{hostvars[inventory_hostname].ansible_ssh_host | default('')}} 2>/dev/null 
                           | grep -q open && exit 0 ||
         echo 'false {{inventory_hostname}}' | tee -a /tmp/deploy.tmp
         "
  delegate_to: 127.0.0.1
  ignore_errors: true
  
- local_action: command cat /tmp/check.tmp
  run_once: true
  register: errs
  
- local_action: debug var=err
  run_once: true
 
- name: Are all hosts present?
  shell: /bin/bash /tmp/check.tmp
  delegate_to: 127.0.0.1
  no_log: True
  
# Ckeck packages
- setup:
    filter: ansible*

- name: Ensure all packages have been installed
  package:
    state: present 
    name: "{{ item }}"
  with_items:
        - git
        - tar
       
