---

- file: 
     path: /tmp/deploy.tmp
     state: absent
  run_once: true
  delegate_to: 127.0.0.1
  ignore_errors: true
   
- file: 
     path: /tmp/deploy.tmp
     state: touch
  run_once: true
  delegate_to: 127.0.0.1
     
- name: Pinging ssh protocol
  shell: nmap -p 22 {{inventory_hostname}} | grep open && exit 0 ||
         nmap -p 22  {{hostvars[inventory_hostname].ansible_ssh_host | default('')}} | grep open && exit 0 ||
         nmap -p {{hostvars[inventory_hostname].ansible_ssh_port | default('')}} {{hostvars[inventory_hostname].ansible_ssh_host | default('')}} | grep open && exit 0 ||
         echo 'false' >> /tmp/deploy.tmp
  delegate_to: 127.0.0.1
  ignore_errors: true

- name: Are all hosts present?
  shell: /bin/bash /tmp/deploy.tmp
delegate_to: 127.0.0.1
