---
   
- file: 
     path: /tmp/check.tmp
     state: absent
  run_once: true
  delegate_to: 127.0.0.1
  ignore_errors: true
   
- file: 
     path: /tmp/check.tmp
     state: touch
  run_once: true
  delegate_to: 127.0.0.1
     
- name: Pinging ssh protocol
  shell: "nmap -p {{hostvars[inventory_hostname].ansible_ssh_port | default('22')}} 
                  {{hostvars[inventory_hostname].ansible_ssh_host | default(inventory_hostname)}} 2>/dev/null         
                           | grep -q open && exit 0 ||                  
         echo 'false {{inventory_hostname}}' | tee -a /tmp/check.tmp
         "
  delegate_to: 127.0.0.1
  ignore_errors: true
#  register: ttt
#- debug: var=ttt
  
- local_action: command cat /tmp/check.tmp
  run_once: true
  register: errs
  
- local_action: debug msg="{{errs.stdout_lines}}"
  run_once: true
 
- name: Are all hosts present?
  shell: /bin/bash /tmp/check.tmp
  delegate_to: 127.0.0.1
  no_log: True
  
# Ckeck packages
- setup:
    filter: ansible*

- name: Ensure all packages have been installed
  package:
    state: present 
    name: "{{ item }}"
  with_items:
        - git
        - tar
       
