---

- name: Pinging hosts
  raw: hostname
  register: ping_status
  ignore_errors: true
 
- debug:
    msg: "{{ping_status.stdout}"

- setup:
       filter: ansible_*

- include: "setup.yml"

- include: "update-code.yml"

- include: "cleanup.yml"

