---

- action: ping
  register: ping_status
 
- debug:
    msg: "{{ping_status.ping}}"

- setup:
       filter: ansible_*

- include: "setup.yml"

- include: "update-code.yml"

- include: "cleanup.yml"

