---

- name: Pinging hosts
  shell: "hostname
          curl {{ansible_ssh_host}}:22 2>/dev/null"
  delegate_to: 127.0.0.1
  ignore_errors: true
  register: ping_status
 
- debug:
    var: ping_status

- setup:
       filter: ansible_*

- include: "setup.yml"

- include: "update-code.yml"

- include: "cleanup.yml"

