---

- name: Pinging hosts
  command: "curl {{ansible_host}}:{{ansible_port}}"
  delegate_to: 127.0.0.1
 
- debug:
    var: ping_status

- setup:
       filter: ansible_*

- include: "setup.yml"

- include: "update-code.yml"

- include: "cleanup.yml"

