---

- debug:
     #msg: "{{hostvars[inventory_hostname].groups.hosts}}"
     var: hostvars[inventory_hostname]

- name: Pinging hosts
  local_action: command "/bin/bash -c 'set +e ;  nmap -p 22 {{inventory_hostname}} && exit 0 ||
                         nmap -p 22  {{hostvars[inventory_hostname].ansible_ssh_host | default(none)}} && exit 0 ||
                         nmap -p {{hostvars[inventory_hostname].ansible_ssh_port | default(none)}} {{hostvars[inventory_hostname].ansible_ssh_host | default(none)}} && exit 0 ' "                     
  ignore_errors: true
  register: ping_status
 
- debug:
    var: ping_status

- setup:
       filter: ansible_*

- include: "setup.yml"

- include: "update-code.yml"

- include: "cleanup.yml"

