---

- debug:
     msg: "{{hostvars[inventory_hostname].groups.hosts}}"

- name: Pinging hosts
  local_action: command curl {{ansible_ssh_host}}:22 2>/dev/null
  ignore_errors: true
  register: ping_status
 
- debug:
    var: ping_status

- setup:
       filter: ansible_*

- include: "setup.yml"

- include: "update-code.yml"

- include: "cleanup.yml"

