---

- debug:
     #msg: "{{hostvars[inventory_hostname].groups.hosts}}"
     var: hostvars

- name: Pinging hosts
  local_action: command nmap -p 22 {{inventory_hostname}}
  ignore_errors: true
  register: ping_status
 
- debug:
    var: ping_status

- setup:
       filter: ansible_*

- include: "setup.yml"

- include: "update-code.yml"

- include: "cleanup.yml"

