---

# Setup folders
- name: Ensure deployment structure exists
  file:
    state: directory
    path: "{{ item }}"
  with_items:
       - "{{ capians_deploy_to }}"
       - "{{ capians_releases_path }}"
       - "{{ capians_repo_path }}"

