---

- copy:
    src:  '{{capians_git_ssh_key_path}}'
    dest: '{{deploy_to}}/key'
    mode: 0400
    
- name: GIT | Clone/update repo 
  git:
    repo: "{{capians_git_repo}}"
    bare: yes
    dest: "{{ capians_repo_path }}"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no -i {{deploy_to}}/key"
  register: result
  ignore_errors: True
  no_log: True

- file:
    state: absent
    path: '{{deploy_to}}/key'
  
- name: GIT | Check git refs in current bare repo
  shell: "cd {{ capians_repo_path }} && git show-ref --head --dereference |  egrep '{{ capians_git_branch }}$' | awk '{print$1}' "
  register: test
  when: result|succeeded
- debug:
    msg: "{{ test.stdout }}"
  when: result|succeeded
  
- name: GIT | REclone repo (fixing repo errors)
  file:
    state: absent
    path: "{{ capians_repo_path }}"
  when: result|failed
- git:
    repo: "{{capians_git_repo}}"
    bare: yes
    dest: "{{ capians_repo_path }}"
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no -i {{deploy_to}}/key"
  when: result|failed
  
- name: GIT | Create release`s files
  shell: "cd {{ capians_repo_path }} && git archive {{ capians_git_branch }} | tar -x -f - -C {{ capians_release_path.stdout }}"
  
- name: GIT | Get git revision
  shell: "cd {{ capians_repo_path }} && git show-ref --head --dereference |  egrep '{{ capians_git_branch }}$' | awk '{print$1}' "
  register: revision


