---

- include_tasks: "../deploy/tasks/check.yml"

- name: Get previous release path
  shell: "echo {{ capians_releases_path }}/$(ls -1t {{ capians_releases_path }} | head -2 | tail -1)"
  register: previous_release_path
  
- name: Get brocken release path
  shell: "echo {{ capians_releases_path }}/$(ls -1t {{ capians_releases_path }} | head -1)"
  register: current_release_path

- include_tasks: "check.yml"

- include_tasks: "custom/pre_symlink_once.yml"

- include_tasks: "custom/pre_symlink.yml"

- include_tasks: "symlink.yml"

- include_tasks: "custom/after_symlink.yml"

- include_tasks: "custom/after_symlink_once.yml"

