---

- name: Get stats current symlink 
  stat:
    path: "{{ capians_deploy_to }}/current"
  register: stat_current_dir


- name: Delete brocken release
  file:
    path: "{{ stat_current_dir.stat.lnk_source }}"
    state: absent  
  
  # Performs symlink exchange
- name: Change softlink to new release
  file:
    state: link
    path: "{{ capians_deploy_to }}/current"
    src:   "{{ previous_release_path.stdout }}"

  
- name: Rollback register
  shell: 'echo "rollback was done to REVISION: $(cat {{ previous_release_path.stdout }}/REVISION )" >> {{ capians_revision }}'
