---

- name: SCRIPT rollback after_symlink
  script: roles/rollback/tasks/custom/after_symlink.sh  "{{previous_release_path.stdout}}" "{{capians_deploy_to}}"
  register: sometext

- debug:
     msg: "{{sometext.stdout_lines}}"
