---

- name: SCRIPT rollback pre_symlink
  script: roles/rollback/tasks/custom/pre_symlink.sh  "{{capians_release_path.stdout}}" "{{capians_deploy_to}}"
  register: sometext

- debug:
     msg: "{{sometext.stdout_lines}}"
