---

- name: SCRIPT rollback pre_symlink
  script: roles/rollback/tasks/custom/pre_symlink.sh  "{{previous_release_path.stdout}}" "{{capians_deploy_to}}"
  register: sometext
  ignore_errors: yes

- debug:
     msg: "{{sometext.stdout_lines}}"
     
- name: Delete release if it is brocken
  file:
     path: "{{previous_release_path.stdout}}"
     state: absent
  when: sometext|failed

- name: Failing cause of errors
  command: /bin/false
  when: sometext|failed  
