---

- name: RUN_ONCE SCRIPT rollback pre_symlink
  script: roles/rollback/tasks/custom/pre_symlink_once.sh  "{{previous_release_path.stdout}}" "{{capians_deploy_to}}"
  run_once: yes
  register: sometext

- debug:
     msg: "{{sometext.stdout_lines}}"
