---

- name: RUN_ONCE SCRIPT deploy after_symlink
  script: roles/deploy/tasks/custom/after_symlink_once.sh  "{{capians_release_path.stdout}}" "{{capians_deploy_to}}"
  run_once: yes
  register: sometext

- debug: 
     msg: "{{sometext.stdout_lines}}"


