---

- name: RUN_ONCE SCRIPT deploy pre_symlink
  script: roles/deploy/tasks/custom/pre_symlink_once.sh  "{{capians_release_path.stdout}}" "{{capians_deploy_to}}"
  run_once: yes
  register: sometext

- debug:
     msg: "{{sometext.stdout_lines}}"
