---

- name: RUN_ONCE SCRIPT deploy pre_symlink
  script: roles/deploy/tasks/custom/pre_symlink_once.sh  "{{capians_release_path.stdout}}" "{{capians_deploy_to}}" 2>&1
  run_once: yes
  register: sometext
  ignore_errors: yes
  
- debug:
     msg: "{{sometext.stdout_lines}}"
 
 
- name: Delete release if it is brocken
  file:
     path: "{{capians_release_path.stdout}}"
     state: absent
  when: sometext|failed

- name: Failing cause of errors
  command: /bin/false
  when: sometext|failed   
